package com.myspace.bc202010dmnlistener;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MyDecisionListener implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public MyDecisionListener() {
    }




}